<a href="https://colab.research.google.com/github/Angelo254/SQL-projects/blob/master/Moringa_Data_Science_Prep_W1_Independent_Project_2019_06_Angelo_Sang_SQL_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Display a list of Uganda_Karamoja_Subcounty_Crop_Yield_Population
%load_ext sql
%sql sqlite://

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

'Connected: @None'

In [ ]:
# Importing the python libraries that we will need in this notebook
#
import csv
import pandas as pd

In [ ]:
# Loading the table from a local CSV file
#
with open('Uganda_Karamoja_Subcounty_Crop_Yield_Population.csv','r') as f:
    Uganda_Karamoja_Subcounty_crop_yield_population = pd.read_csv(f, index_col=0, encoding='utf-8') 

# Then storing it in an SQL table of our in memory sqlite database
#
%sql DROP TABLE if EXISTS Uganda_Karamoja_Subcounty_crop_yield_population;
%sql PERSIST Uganda_Karamoja_Subcounty_crop_yield_population;

 * sqlite://
Done.
 * sqlite://

'Persisted uganda_karamoja_subcounty_crop_yield_population'

In [ ]:
#Display a list of Sub Counties and their population and areas.
%%sql
SELECT 'SUBCOUNTY', "POP","Area" FROM Uganda_Karamoja_Subcounty_Crop_Yield_Population

 * sqlite://
Done.

[('SUBCOUNTY', 17244, 1067176155),
 ('SUBCOUNTY', 52771, 597575188),
 ('SUBCOUNTY', 27389, 23972401),
 ('SUBCOUNTY', 38775, 419111591),
 ('SUBCOUNTY', 65704, 880955930),
 ('SUBCOUNTY', 41273, 652744859),
 ('SUBCOUNTY', 42221, 60801942),
 ('SUBCOUNTY', 38857, 13071455),
 ('SUBCOUNTY', 41454, 67612362),
 ('SUBCOUNTY', 99203, 223116860),
 ('SUBCOUNTY', 60070, 1199409465),
 ('SUBCOUNTY', 33951, 304557831),
 ('SUBCOUNTY', 56870, 228457417),
 ('SUBCOUNTY', 37691, 1742041261),
 ('SUBCOUNTY', 22907, 302572789),
 ('SUBCOUNTY', 31820, 397700845),
 ('SUBCOUNTY', 100919, 1069331387),
 ('SUBCOUNTY', 16608, 1330019236),
 ('SUBCOUNTY', 20394, 309577387),
 ('SUBCOUNTY', 24092, 125330583),
 ('SUBCOUNTY', 14377, 188613057),
 ('SUBCOUNTY', 11489, 115941152),
 ('SUBCOUNTY', 12573, 1255760525),
 ('SUBCOUNTY', 18641, 191684465),
 ('SUBCOUNTY', 16834, 250364895),
 ('SUBCOUNTY', 45015, 658008801),
 ('SUBCOUNTY', 22541, 371970302),
 ('SUBCOUNTY', 30181, 596393139),
 ('SUBCOUNTY', 4053, 17207110),
 ('SUBCOUNTY', 11772, 277451997),
 ('SUBCOUNTY', 42115, 596023780),
 ('SUBCOUNTY', 21999, 622266516),
 ('SUBCOUNTY', 7161, 2738777),
 ('SUBCOUNTY', 3272, 2121209),
 ('SUBCOUNTY', 26644, 928683431),
 ('SUBCOUNTY', 1418, 4673094),
 ('SUBCOUNTY', 25905, 553067364),
 ('SUBCOUNTY', 15960, 312709097),
 ('SUBCOUNTY', 22801, 642401705),
 ('SUBCOUNTY', 9929, 435714604),
 ('SUBCOUNTY', 27534, 499776866),
 ('SUBCOUNTY', 46979, 1030623258),
 ('SUBCOUNTY', 18815, 790782350),
 ('SUBCOUNTY', 2503, 118997955),
 ('SUBCOUNTY', 17834, 125857565),
 ('SUBCOUNTY', 29495, 338252511),
 ('SUBCOUNTY', 8010, 150906375),
 ('SUBCOUNTY', 20790, 158887552),
 ('SUBCOUNTY', 16470, 769609687),
 ('SUBCOUNTY', 23200, 1794470536),
 ('SUBCOUNTY', 41493, 2069554899),
 ('SUBCOUNTY', 16588, 839293722)]

In [ ]:
#Sort the list of districts by total crop area (descending order)
%%sql
SELECT "DISTRICT_NAME", "Crop_Area_Ha" FROM Uganda_Karamoja_Subcounty_Crop_Yield_Population
ORDER BY "Crop_Area_Ha" DESC;

 * sqlite://
Done.

[('KOTIDO', 13587.990759999999),
 ('KOTIDO', 13278.52043),
 ('KOTIDO', 10398.24939),
 ('KOTIDO', 7087.823334000001),
 ('KOTIDO', 7023.533691),
 ('KAABONG', 6890.699234000001),
 ('NAPAK', 6471.047334000001),
 ('NAKAPIRIPIRIT', 5793.5076229999995),
 ('NAKAPIRIPIRIT', 5759.618906000001),
 ('NAPAK', 5473.443674),
 ('NAKAPIRIPIRIT', 5079.779088),
 ('KAABONG', 3934.432233),
 ('NAKAPIRIPIRIT', 3276.653762),
 ('NAKAPIRIPIRIT', 3264.534948),
 ('NAPAK', 3120.318045),
 ('NAPAK', 2990.847377),
 ('KAABONG', 2834.349905),
 ('KAABONG', 2700.676313),
 ('AMUDAT', 2513.27183),
 ('MOROTO', 2480.1219),
 ('KAABONG', 2365.259806),
 ('MOROTO', 2217.2907170000003),
 ('NAKAPIRIPIRIT', 2008.0681690000001),
 ('KAABONG', 1890.248613),
 ('NAPAK', 1849.966589),
 ('KOTIDO', 1656.5318550000002),
 ('AMUDAT', 1651.99842),
 ('AMUDAT', 1539.401382),
 ('KAABONG', 1494.047587),
 ('KAABONG', 1491.771813),
 ('ABIM', 1266.109868),
 ('NAPAK', 1215.227445),
 ('NAKAPIRIPIRIT', 1161.3902289999999),
 ('MOROTO', 1111.664207),
 ('NAPAK', 1031.196285),
 ('KAABONG', 1021.31699),
 ('ABIM', 999.3715888),
 ('KAABONG', 997.1610206),
 ('KAABONG', 967.3367266),
 ('KAABONG', 957.4939457999999),
 ('ABIM', 925.0541302000001),
 ('ABIM', 792.8987889),
 ('NAPAK', 792.2492731000001),
 ('ABIM', 788.4628001),
 ('ABIM', 698.1712182),
 ('KAABONG', 401.7978207),
 ('KAABONG', 175.08052659999998),
 ('MOROTO', 145.243518),
 ('AMUDAT', 60.77208552),
 ('NAKAPIRIPIRIT', 29.14576036),
 ('MOROTO', 0.322315707),
 ('MOROTO', 0.17139046100000002)]

In [ ]:
#Select only the Sub counties from the Moroto district, order them alphabetically 
#and show their production of sorghum
%%sql
SELECT "SUBCOUNTY_NAME", "DISTRICT_NAME", "S_Prod_Tot" FROM Uganda_Karamoja_Subcounty_Crop_Yield_Population
WHERE DISTRICT_NAME = "MOROTO"
ORDER BY "DISTRICT_NAME" ASC

 * sqlite://
Done.

[('KATIKEKILE', 'MOROTO', 9379.029413),
 ('NADUNGET', 'MOROTO', 321630.539),
 ('TAPAC', 'MOROTO', 49251.66081),
 ('NORTHERN DIVISION', 'MOROTO', 17.28125956),
 ('SOUTHERN DIVISION', 'MOROTO', 19.67486547),
 ('RUPA', 'MOROTO', 227298.5184)]

In [ ]:
#Compute the total Maize production per District
%%sql
SELECT "DISTRICT_NAME", "M_Prod_Tot" FROM Uganda_Karamoja_Subcounty_Crop_Yield_Population

 * sqlite://
Done.

[('KOTIDO', 600723.8929),
 ('KOTIDO', 959201.3825),
 ('KOTIDO', 9991.488268000001),
 ('KOTIDO', 38971.65908),
 ('KOTIDO', 221609.5114),
 ('KOTIDO', 179681.139),
 ('KAABONG', 10181.201),
 ('KAABONG', 22772.636430000002),
 ('KAABONG', 59450.18942),
 ('KAABONG', 209806.09699999998),
 ('KAABONG', 392864.0158),
 ('KAABONG', 744375.6816),
 ('KAABONG', 976952.2116),
 ('KAABONG', 1412776.9819999998),
 ('KAABONG', 990983.0661),
 ('KAABONG', 61343.42645),
 ('KAABONG', 836095.3853),
 ('KAABONG', 201613.3805),
 ('KAABONG', 934881.6576),
 ('KAABONG', 136265.6835),
 ('ABIM', 306951.8167),
 ('ABIM', 299895.1917),
 ('ABIM', 446294.5944),
 ('ABIM', 322910.6857),
 ('ABIM', 288070.5968),
 ('AMUDAT', 1415591.549),
 ('AMUDAT', 788123.4753),
 ('AMUDAT', 1340672.952),
 ('AMUDAT', 2081.356199),
 ('MOROTO', 56404.03821),
 ('MOROTO', 41687.926510000005),
 ('MOROTO', 168139.0047),
 ('MOROTO', 46.22440465),
 ('MOROTO', 0.0),
 ('NAKAPIRIPIRIT', 963132.1158),
 ('NAKAPIRIPIRIT', 34961.59076),
 ('NAKAPIRIPIRIT', 4365057.517),
 ('NAKAPIRIPIRIT', 602917.1224),
 ('NAKAPIRIPIRIT', 803244.7393),
 ('NAKAPIRIPIRIT', 63990.504570000005),
 ('NAKAPIRIPIRIT', 93265.78063),
 ('NAPAK', 3354666.348),
 ('NAPAK', 1006139.305),
 ('NAPAK', 301833.0535),
 ('NAPAK', 39634.98127),
 ('NAPAK', 143401.6585),
 ('NAPAK', 291177.2726),
 ('NAPAK', 36017.149410000005),
 ('ABIM', 258010.2444),
 ('NAPAK', 414509.6206),
 ('MOROTO', 155838.875),
 ('NAKAPIRIPIRIT', 1198586.875)]

In [ ]:
#Compute the number of Sub counties where Maize is produced 
#and the total Maize production per District
%%sql
SELECT "SUBCOUNTY_NAME", "DISTRICT_NAME", "M_Area_Ha", "M_Prod_Tot" FROM Uganda_Karamoja_Subcounty_Crop_Yield_Population
WHERE "M_Area_Ha" > 0

 * sqlite://
Done.

[('KACHERI', 'KOTIDO', 528.1242294, 600723.8929),
 ('KOTIDO', 'KOTIDO', 824.7670809, 959201.3825),
 ('KOTIDO TOWN COUNCIL', 'KOTIDO', 8.561643817, 9991.488268000001),
 ('NAKAPERIMORU', 'KOTIDO', 45.72171184, 38971.65908),
 ('PANYANGARA', 'KOTIDO', 172.6119139, 221609.5114),
 ('RENGEN', 'KOTIDO', 171.5857036, 179681.139),
 ('KAABONG  EAST', 'KAABONG', 15.66040911, 10181.201),
 ('KAABONG TOWN COUNCIL', 'KAABONG', 18.52618562, 22772.636430000002),
 ('KAABONG WEST', 'KAABONG', 56.27535518, 59450.18942),
 ('KALAPATA', 'KAABONG', 331.2257949, 209806.09699999998),
 ('KAMION', 'KAABONG', 549.8633367000001, 392864.0158),
 ('KAPEDO', 'KAABONG', 722.6498686000001, 744375.6816),
 ('KATHILE', 'KAABONG', 867.8731713, 976952.2116),
 ('KAWALAKOL', 'KAABONG', 1620.876815, 1412776.9819999998),
 ('LOBALANGIT', 'KAABONG', 1005.8773960000001, 990983.0661),
 ('LODIKO', 'KAABONG', 75.24439792, 61343.42645),
 ('LOLELIA', 'KAABONG', 656.5863967, 836095.3853),
 ('LOYORO', 'KAABONG', 154.68223909999998, 201613.3805),
 ('NAPORE (KARENGA)', 'KAABONG', 1221.532726, 934881.6576),
 ('SIDOK', 'KAABONG', 97.5422428, 136265.6835),
 ('ABIM', 'ABIM', 259.4493301, 306951.8167),
 ('ABIM TOWN COUNCIL', 'ABIM', 282.61309389999997, 299895.1917),
 ('ALEREK', 'ABIM', 354.4490355, 446294.5944),
 ('LOTUKEI', 'ABIM', 321.8473311, 322910.6857),
 ('MORULEM', 'ABIM', 299.1517243, 288070.5968),
 ('KARITA', 'AMUDAT', 1100.15237, 1415591.549),
 ('LOROO', 'AMUDAT', 658.9176121, 788123.4753),
 ('AMUDAT', 'AMUDAT', 972.1742458999998, 1340672.952),
 ('AMUDAT TOWN COUNCIL', 'AMUDAT', 2.416785505, 2081.356199),
 ('KATIKEKILE', 'MOROTO', 103.27756219999999, 56404.03821),
 ('NADUNGET', 'MOROTO', 70.50569361, 41687.926510000005),
 ('TAPAC', 'MOROTO', 793.2370943, 168139.0047),
 ('NORTHERN DIVISION', 'MOROTO', 0.19137495100000002, 46.22440465),
 ('LOREGAE', 'NAKAPIRIPIRIT', 864.1105686000001, 963132.1158),
 ('NAKAPIRIPIRIT TOWN COUNCIL', 'NAKAPIRIPIRIT', 27.79576662, 34961.59076),
 ('NAMALU', 'NAKAPIRIPIRIT', 3293.74946, 4365057.517),
 ('KAKOMONGOLE', 'NAKAPIRIPIRIT', 457.35760539999995, 602917.1224),
 ('LOLACHAT', 'NAKAPIRIPIRIT', 655.2122757000001, 803244.7393),
 ('LORENGEDWAT', 'NAKAPIRIPIRIT', 80.41702686, 63990.504570000005),
 ('NABILATUK', 'NAKAPIRIPIRIT', 87.47454924, 93265.78063),
 ('IRIIRI', 'NAPAK', 3840.6980810000005, 3354666.348),
 ('LOPEEI', 'NAPAK', 955.2646167000001, 1006139.305),
 ('LORENGECORA', 'NAPAK', 358.5503345, 301833.0535),
 ('LOTOME', 'NAPAK', 78.03589239, 39634.98127),
 ('MATANY', 'NAPAK', 288.329571, 143401.6585),
 ('NAPAK TOWN COUNCIL', 'NAPAK', 401.1734419, 291177.2726),
 ('NGOLERIET', 'NAPAK', 68.12400511, 36017.149410000005),
 ('NYAKWAE', 'ABIM', 331.1113402, 258010.2444),
 ('LOKOPO', 'NAPAK', 553.5431231000001, 414509.6206),
 ('RUPA', 'MOROTO', 222.8388813, 155838.875),
 ('MORUITA', 'NAKAPIRIPIRIT', 959.6711616, 1198586.875)]

In [ ]:
#Compute the overall Crop area in all Sub counties where population is over 20000
%%sql
SELECT "SUBCOUNTY_NAME", "Crop_Area_Ha" FROM Uganda_Karamoja_Subcounty_Crop_Yield_Population
WHERE "POP" > 20000

 * sqlite://
Done.

[('KOTIDO', 13587.990759999999),
 ('KOTIDO TOWN COUNCIL', 1656.5318550000002),
 ('NAKAPERIMORU', 7087.823334000001),
 ('PANYANGARA', 10398.24939),
 ('RENGEN', 13278.52043),
 ('KAABONG  EAST', 1021.31699),
 ('KAABONG TOWN COUNCIL', 175.08052659999998),
 ('KAABONG WEST', 967.3367266),
 ('KALAPATA', 2834.349905),
 ('KAMION', 997.1610206),
 ('KAPEDO', 2365.259806),
 ('KATHILE', 6890.699234000001),
 ('KAWALAKOL', 3934.432233),
 ('LOBALANGIT', 1890.248613),
 ('LODIKO', 401.7978207),
 ('LOLELIA', 2700.676313),
 ('NAPORE (KARENGA)', 1494.047587),
 ('SIDOK', 957.4939457999999),
 ('KARITA', 2513.27183),
 ('LOROO', 1539.401382),
 ('AMUDAT', 1651.99842),
 ('NADUNGET', 2480.1219),
 ('TAPAC', 1111.664207),
 ('LOREGAE', 5759.618906000001),
 ('NAMALU', 5793.5076229999995),
 ('LOLACHAT', 5079.779088),
 ('NABILATUK', 3276.653762),
 ('IRIIRI', 5473.443674),
 ('MATANY', 2990.847377),
 ('NGOLERIET', 1215.227445),
 ('LOKOPO', 6471.047334000001),
 ('RUPA', 2217.2907170000003)]

In [ ]:
#Sort the Maize production in descending order by Districts,
#only taking into account Sub counties where Maize area is larger than Sorghum area,
#and display the number of Sub counties per district matching that criteria
%%sql
SELECT "SUBCOUNTY_NAME", "DISTRICT_NAME", "S_Area_Ha", "M_Area_Ha" FROM Uganda_Karamoja_Subcounty_Crop_Yield_Population
WHERE "S_Area_Ha" < "M_Area_Ha"
ORDER BY "DISTRICT_NAME" DESC

 * sqlite://
Done.

[('IRIIRI', 'NAPAK', 1550.9445699999999, 3840.6980810000005),
 ('NAPAK TOWN COUNCIL', 'NAPAK', 386.1580327, 401.1734419),
 ('NAKAPIRIPIRIT TOWN COUNCIL', 'NAKAPIRIPIRIT', 1.3399191590000001, 27.79576662),
 ('NAMALU', 'NAKAPIRIPIRIT', 2197.572106, 3293.74946),
 ('MORUITA', 'NAKAPIRIPIRIT', 185.2834449, 959.6711616),
 ('KATIKEKILE', 'MOROTO', 30.15704817, 103.27756219999999),
 ('TAPAC', 'MOROTO', 315.979223, 793.2370943),
 ('NORTHERN DIVISION', 'MOROTO', 0.130940756, 0.19137495100000002),
 ('KAMION', 'KAABONG', 411.8070005, 549.8633367000001),
 ('LOBALANGIT', 'KAABONG', 879.0023395, 1005.8773960000001),
 ('NAPORE (KARENGA)', 'KAABONG', 267.559128, 1221.532726),
 ('AMUDAT', 'AMUDAT', 676.7832664, 972.1742458999998)]